/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as MfaRouteImport } from './routes/mfa'
import { Route as IdentityRouteImport } from './routes/identity'
import { Route as IndexRouteImport } from './routes/index'

const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaRoute = MfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityRoute = IdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/identity': typeof IdentityRoute
  '/mfa': typeof MfaRoute
  '/otp': typeof OtpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/identity': typeof IdentityRoute
  '/mfa': typeof MfaRoute
  '/otp': typeof OtpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/identity': typeof IdentityRoute
  '/mfa': typeof MfaRoute
  '/otp': typeof OtpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/identity' | '/mfa' | '/otp'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/identity' | '/mfa' | '/otp'
  id: '__root__' | '/' | '/identity' | '/mfa' | '/otp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdentityRoute: typeof IdentityRoute
  MfaRoute: typeof MfaRoute
  OtpRoute: typeof OtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa': {
      id: '/mfa'
      path: '/mfa'
      fullPath: '/mfa'
      preLoaderRoute: typeof MfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity': {
      id: '/identity'
      path: '/identity'
      fullPath: '/identity'
      preLoaderRoute: typeof IdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdentityRoute: IdentityRoute,
  MfaRoute: MfaRoute,
  OtpRoute: OtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
