/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as IdentityRouteImport } from './routes/identity'
import { Route as CodesRouteImport } from './routes/codes'
import { Route as IndexRouteImport } from './routes/index'

const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityRoute = IdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const CodesRoute = CodesRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/codes': typeof CodesRoute
  '/identity': typeof IdentityRoute
  '/recovery': typeof RecoveryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/codes': typeof CodesRoute
  '/identity': typeof IdentityRoute
  '/recovery': typeof RecoveryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/codes': typeof CodesRoute
  '/identity': typeof IdentityRoute
  '/recovery': typeof RecoveryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/codes' | '/identity' | '/recovery'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/codes' | '/identity' | '/recovery'
  id: '__root__' | '/' | '/codes' | '/identity' | '/recovery'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodesRoute: typeof CodesRoute
  IdentityRoute: typeof IdentityRoute
  RecoveryRoute: typeof RecoveryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity': {
      id: '/identity'
      path: '/identity'
      fullPath: '/identity'
      preLoaderRoute: typeof IdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codes': {
      id: '/codes'
      path: '/codes'
      fullPath: '/codes'
      preLoaderRoute: typeof CodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodesRoute: CodesRoute,
  IdentityRoute: IdentityRoute,
  RecoveryRoute: RecoveryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
